/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference/index'
import { Route as ReadIndexRouteImport } from './routes/read/index'
import { Route as QabalahIndexRouteImport } from './routes/qabalah/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as CustomIndexRouteImport } from './routes/custom/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as AstrologyIndexRouteImport } from './routes/astrology/index'
import { Route as StudySettingsRouteImport } from './routes/study/settings'
import { Route as StudySessionRouteImport } from './routes/study/session'
import { Route as SettingsTraditionsRouteImport } from './routes/settings/traditions'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNavRouteImport } from './routes/settings/nav'
import { Route as SettingsManualRouteImport } from './routes/settings/manual'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as SettingsArtRouteImport } from './routes/settings/art'
import { Route as SettingsAccessibilityRouteImport } from './routes/settings/accessibility'
import { Route as ReferenceSephirothicMatrixRouteImport } from './routes/reference/sephirothic-matrix'
import { Route as ReferencePlanetaryMatrixRouteImport } from './routes/reference/planetary-matrix'
import { Route as ReferenceLenormandCombinationsRouteImport } from './routes/reference/lenormand-combinations'
import { Route as ReferenceIchingTrigramMatrixRouteImport } from './routes/reference/iching-trigram-matrix'
import { Route as ReferenceGeomancyShieldChartRouteImport } from './routes/reference/geomancy-shield-chart'
import { Route as ReferenceChineseZodiacCompatibilityRouteImport } from './routes/reference/chinese-zodiac-compatibility'
import { Route as ReferenceAstrologicalDignitiesRouteImport } from './routes/reference/astrological-dignities'
import { Route as ReferenceCanonicalNameRouteImport } from './routes/reference/$canonicalName'
import { Route as ReadSpreadsRouteImport } from './routes/read/spreads'
import { Route as ReadRecordRouteImport } from './routes/read/record'
import { Route as ReadDrawRouteImport } from './routes/read/draw'
import { Route as ReadDecksRouteImport } from './routes/read/decks'
import { Route as QabalahNumerologyRouteImport } from './routes/qabalah/numerology'
import { Route as QabalahGematriaRouteImport } from './routes/qabalah/gematria'
import { Route as JournalStatsRouteImport } from './routes/journal/stats'
import { Route as CustomTraditionsRouteImport } from './routes/custom/traditions'
import { Route as CustomNewRouteImport } from './routes/custom/new'
import { Route as CustomCnRouteImport } from './routes/custom/$cn'
import { Route as AstrologyNewRouteImport } from './routes/astrology/new'
import { Route as AstrologyAnimateRouteImport } from './routes/astrology/animate'
import { Route as AstrologyIdRouteImport } from './routes/astrology/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => rootRouteImport,
} as any)
const QabalahIndexRoute = QabalahIndexRouteImport.update({
  id: '/qabalah/',
  path: '/qabalah/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomIndexRoute = CustomIndexRouteImport.update({
  id: '/custom/',
  path: '/custom/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyIndexRoute = AstrologyIndexRouteImport.update({
  id: '/astrology/',
  path: '/astrology/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySettingsRoute = StudySettingsRouteImport.update({
  id: '/study/settings',
  path: '/study/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySessionRoute = StudySessionRouteImport.update({
  id: '/study/session',
  path: '/study/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTraditionsRoute = SettingsTraditionsRouteImport.update({
  id: '/settings/traditions',
  path: '/settings/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNavRoute = SettingsNavRouteImport.update({
  id: '/settings/nav',
  path: '/settings/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsManualRoute = SettingsManualRouteImport.update({
  id: '/settings/manual',
  path: '/settings/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings/data',
  path: '/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsArtRoute = SettingsArtRouteImport.update({
  id: '/settings/art',
  path: '/settings/art',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: '/settings/accessibility',
  path: '/settings/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSephirothicMatrixRoute =
  ReferenceSephirothicMatrixRouteImport.update({
    id: '/reference/sephirothic-matrix',
    path: '/reference/sephirothic-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferencePlanetaryMatrixRoute =
  ReferencePlanetaryMatrixRouteImport.update({
    id: '/reference/planetary-matrix',
    path: '/reference/planetary-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceLenormandCombinationsRoute =
  ReferenceLenormandCombinationsRouteImport.update({
    id: '/reference/lenormand-combinations',
    path: '/reference/lenormand-combinations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceIchingTrigramMatrixRoute =
  ReferenceIchingTrigramMatrixRouteImport.update({
    id: '/reference/iching-trigram-matrix',
    path: '/reference/iching-trigram-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceGeomancyShieldChartRoute =
  ReferenceGeomancyShieldChartRouteImport.update({
    id: '/reference/geomancy-shield-chart',
    path: '/reference/geomancy-shield-chart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceChineseZodiacCompatibilityRoute =
  ReferenceChineseZodiacCompatibilityRouteImport.update({
    id: '/reference/chinese-zodiac-compatibility',
    path: '/reference/chinese-zodiac-compatibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceAstrologicalDignitiesRoute =
  ReferenceAstrologicalDignitiesRouteImport.update({
    id: '/reference/astrological-dignities',
    path: '/reference/astrological-dignities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceCanonicalNameRoute = ReferenceCanonicalNameRouteImport.update({
  id: '/reference/$canonicalName',
  path: '/reference/$canonicalName',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSpreadsRoute = ReadSpreadsRouteImport.update({
  id: '/read/spreads',
  path: '/read/spreads',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRecordRoute = ReadRecordRouteImport.update({
  id: '/read/record',
  path: '/read/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadDrawRoute = ReadDrawRouteImport.update({
  id: '/read/draw',
  path: '/read/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadDecksRoute = ReadDecksRouteImport.update({
  id: '/read/decks',
  path: '/read/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const QabalahNumerologyRoute = QabalahNumerologyRouteImport.update({
  id: '/qabalah/numerology',
  path: '/qabalah/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const QabalahGematriaRoute = QabalahGematriaRouteImport.update({
  id: '/qabalah/gematria',
  path: '/qabalah/gematria',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalStatsRoute = JournalStatsRouteImport.update({
  id: '/journal/stats',
  path: '/journal/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTraditionsRoute = CustomTraditionsRouteImport.update({
  id: '/custom/traditions',
  path: '/custom/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomNewRoute = CustomNewRouteImport.update({
  id: '/custom/new',
  path: '/custom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomCnRoute = CustomCnRouteImport.update({
  id: '/custom/$cn',
  path: '/custom/$cn',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyNewRoute = AstrologyNewRouteImport.update({
  id: '/astrology/new',
  path: '/astrology/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyAnimateRoute = AstrologyAnimateRouteImport.update({
  id: '/astrology/animate',
  path: '/astrology/animate',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyIdRoute = AstrologyIdRouteImport.update({
  id: '/astrology/$id',
  path: '/astrology/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrology/$id': typeof AstrologyIdRoute
  '/astrology/animate': typeof AstrologyAnimateRoute
  '/astrology/new': typeof AstrologyNewRoute
  '/custom/$cn': typeof CustomCnRoute
  '/custom/new': typeof CustomNewRoute
  '/custom/traditions': typeof CustomTraditionsRoute
  '/journal/stats': typeof JournalStatsRoute
  '/qabalah/gematria': typeof QabalahGematriaRoute
  '/qabalah/numerology': typeof QabalahNumerologyRoute
  '/read/decks': typeof ReadDecksRoute
  '/read/draw': typeof ReadDrawRoute
  '/read/record': typeof ReadRecordRoute
  '/read/spreads': typeof ReadSpreadsRoute
  '/reference/$canonicalName': typeof ReferenceCanonicalNameRoute
  '/reference/astrological-dignities': typeof ReferenceAstrologicalDignitiesRoute
  '/reference/chinese-zodiac-compatibility': typeof ReferenceChineseZodiacCompatibilityRoute
  '/reference/geomancy-shield-chart': typeof ReferenceGeomancyShieldChartRoute
  '/reference/iching-trigram-matrix': typeof ReferenceIchingTrigramMatrixRoute
  '/reference/lenormand-combinations': typeof ReferenceLenormandCombinationsRoute
  '/reference/planetary-matrix': typeof ReferencePlanetaryMatrixRoute
  '/reference/sephirothic-matrix': typeof ReferenceSephirothicMatrixRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/art': typeof SettingsArtRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/manual': typeof SettingsManualRoute
  '/settings/nav': typeof SettingsNavRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/traditions': typeof SettingsTraditionsRoute
  '/study/session': typeof StudySessionRoute
  '/study/settings': typeof StudySettingsRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/custom/': typeof CustomIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/qabalah/': typeof QabalahIndexRoute
  '/read/': typeof ReadIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrology/$id': typeof AstrologyIdRoute
  '/astrology/animate': typeof AstrologyAnimateRoute
  '/astrology/new': typeof AstrologyNewRoute
  '/custom/$cn': typeof CustomCnRoute
  '/custom/new': typeof CustomNewRoute
  '/custom/traditions': typeof CustomTraditionsRoute
  '/journal/stats': typeof JournalStatsRoute
  '/qabalah/gematria': typeof QabalahGematriaRoute
  '/qabalah/numerology': typeof QabalahNumerologyRoute
  '/read/decks': typeof ReadDecksRoute
  '/read/draw': typeof ReadDrawRoute
  '/read/record': typeof ReadRecordRoute
  '/read/spreads': typeof ReadSpreadsRoute
  '/reference/$canonicalName': typeof ReferenceCanonicalNameRoute
  '/reference/astrological-dignities': typeof ReferenceAstrologicalDignitiesRoute
  '/reference/chinese-zodiac-compatibility': typeof ReferenceChineseZodiacCompatibilityRoute
  '/reference/geomancy-shield-chart': typeof ReferenceGeomancyShieldChartRoute
  '/reference/iching-trigram-matrix': typeof ReferenceIchingTrigramMatrixRoute
  '/reference/lenormand-combinations': typeof ReferenceLenormandCombinationsRoute
  '/reference/planetary-matrix': typeof ReferencePlanetaryMatrixRoute
  '/reference/sephirothic-matrix': typeof ReferenceSephirothicMatrixRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/art': typeof SettingsArtRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/manual': typeof SettingsManualRoute
  '/settings/nav': typeof SettingsNavRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/traditions': typeof SettingsTraditionsRoute
  '/study/session': typeof StudySessionRoute
  '/study/settings': typeof StudySettingsRoute
  '/astrology': typeof AstrologyIndexRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/custom': typeof CustomIndexRoute
  '/journal': typeof JournalIndexRoute
  '/qabalah': typeof QabalahIndexRoute
  '/read': typeof ReadIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrology/$id': typeof AstrologyIdRoute
  '/astrology/animate': typeof AstrologyAnimateRoute
  '/astrology/new': typeof AstrologyNewRoute
  '/custom/$cn': typeof CustomCnRoute
  '/custom/new': typeof CustomNewRoute
  '/custom/traditions': typeof CustomTraditionsRoute
  '/journal/stats': typeof JournalStatsRoute
  '/qabalah/gematria': typeof QabalahGematriaRoute
  '/qabalah/numerology': typeof QabalahNumerologyRoute
  '/read/decks': typeof ReadDecksRoute
  '/read/draw': typeof ReadDrawRoute
  '/read/record': typeof ReadRecordRoute
  '/read/spreads': typeof ReadSpreadsRoute
  '/reference/$canonicalName': typeof ReferenceCanonicalNameRoute
  '/reference/astrological-dignities': typeof ReferenceAstrologicalDignitiesRoute
  '/reference/chinese-zodiac-compatibility': typeof ReferenceChineseZodiacCompatibilityRoute
  '/reference/geomancy-shield-chart': typeof ReferenceGeomancyShieldChartRoute
  '/reference/iching-trigram-matrix': typeof ReferenceIchingTrigramMatrixRoute
  '/reference/lenormand-combinations': typeof ReferenceLenormandCombinationsRoute
  '/reference/planetary-matrix': typeof ReferencePlanetaryMatrixRoute
  '/reference/sephirothic-matrix': typeof ReferenceSephirothicMatrixRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/art': typeof SettingsArtRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/manual': typeof SettingsManualRoute
  '/settings/nav': typeof SettingsNavRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/traditions': typeof SettingsTraditionsRoute
  '/study/session': typeof StudySessionRoute
  '/study/settings': typeof StudySettingsRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/custom/': typeof CustomIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/qabalah/': typeof QabalahIndexRoute
  '/read/': typeof ReadIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astrology/$id'
    | '/astrology/animate'
    | '/astrology/new'
    | '/custom/$cn'
    | '/custom/new'
    | '/custom/traditions'
    | '/journal/stats'
    | '/qabalah/gematria'
    | '/qabalah/numerology'
    | '/read/decks'
    | '/read/draw'
    | '/read/record'
    | '/read/spreads'
    | '/reference/$canonicalName'
    | '/reference/astrological-dignities'
    | '/reference/chinese-zodiac-compatibility'
    | '/reference/geomancy-shield-chart'
    | '/reference/iching-trigram-matrix'
    | '/reference/lenormand-combinations'
    | '/reference/planetary-matrix'
    | '/reference/sephirothic-matrix'
    | '/settings/accessibility'
    | '/settings/art'
    | '/settings/credits'
    | '/settings/data'
    | '/settings/manual'
    | '/settings/nav'
    | '/settings/privacy'
    | '/settings/traditions'
    | '/study/session'
    | '/study/settings'
    | '/astrology/'
    | '/bookmarks/'
    | '/calendar/'
    | '/custom/'
    | '/journal/'
    | '/qabalah/'
    | '/read/'
    | '/reference/'
    | '/settings/'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrology/$id'
    | '/astrology/animate'
    | '/astrology/new'
    | '/custom/$cn'
    | '/custom/new'
    | '/custom/traditions'
    | '/journal/stats'
    | '/qabalah/gematria'
    | '/qabalah/numerology'
    | '/read/decks'
    | '/read/draw'
    | '/read/record'
    | '/read/spreads'
    | '/reference/$canonicalName'
    | '/reference/astrological-dignities'
    | '/reference/chinese-zodiac-compatibility'
    | '/reference/geomancy-shield-chart'
    | '/reference/iching-trigram-matrix'
    | '/reference/lenormand-combinations'
    | '/reference/planetary-matrix'
    | '/reference/sephirothic-matrix'
    | '/settings/accessibility'
    | '/settings/art'
    | '/settings/credits'
    | '/settings/data'
    | '/settings/manual'
    | '/settings/nav'
    | '/settings/privacy'
    | '/settings/traditions'
    | '/study/session'
    | '/study/settings'
    | '/astrology'
    | '/bookmarks'
    | '/calendar'
    | '/custom'
    | '/journal'
    | '/qabalah'
    | '/read'
    | '/reference'
    | '/settings'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/astrology/$id'
    | '/astrology/animate'
    | '/astrology/new'
    | '/custom/$cn'
    | '/custom/new'
    | '/custom/traditions'
    | '/journal/stats'
    | '/qabalah/gematria'
    | '/qabalah/numerology'
    | '/read/decks'
    | '/read/draw'
    | '/read/record'
    | '/read/spreads'
    | '/reference/$canonicalName'
    | '/reference/astrological-dignities'
    | '/reference/chinese-zodiac-compatibility'
    | '/reference/geomancy-shield-chart'
    | '/reference/iching-trigram-matrix'
    | '/reference/lenormand-combinations'
    | '/reference/planetary-matrix'
    | '/reference/sephirothic-matrix'
    | '/settings/accessibility'
    | '/settings/art'
    | '/settings/credits'
    | '/settings/data'
    | '/settings/manual'
    | '/settings/nav'
    | '/settings/privacy'
    | '/settings/traditions'
    | '/study/session'
    | '/study/settings'
    | '/astrology/'
    | '/bookmarks/'
    | '/calendar/'
    | '/custom/'
    | '/journal/'
    | '/qabalah/'
    | '/read/'
    | '/reference/'
    | '/settings/'
    | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologyIdRoute: typeof AstrologyIdRoute
  AstrologyAnimateRoute: typeof AstrologyAnimateRoute
  AstrologyNewRoute: typeof AstrologyNewRoute
  CustomCnRoute: typeof CustomCnRoute
  CustomNewRoute: typeof CustomNewRoute
  CustomTraditionsRoute: typeof CustomTraditionsRoute
  JournalStatsRoute: typeof JournalStatsRoute
  QabalahGematriaRoute: typeof QabalahGematriaRoute
  QabalahNumerologyRoute: typeof QabalahNumerologyRoute
  ReadDecksRoute: typeof ReadDecksRoute
  ReadDrawRoute: typeof ReadDrawRoute
  ReadRecordRoute: typeof ReadRecordRoute
  ReadSpreadsRoute: typeof ReadSpreadsRoute
  ReferenceCanonicalNameRoute: typeof ReferenceCanonicalNameRoute
  ReferenceAstrologicalDignitiesRoute: typeof ReferenceAstrologicalDignitiesRoute
  ReferenceChineseZodiacCompatibilityRoute: typeof ReferenceChineseZodiacCompatibilityRoute
  ReferenceGeomancyShieldChartRoute: typeof ReferenceGeomancyShieldChartRoute
  ReferenceIchingTrigramMatrixRoute: typeof ReferenceIchingTrigramMatrixRoute
  ReferenceLenormandCombinationsRoute: typeof ReferenceLenormandCombinationsRoute
  ReferencePlanetaryMatrixRoute: typeof ReferencePlanetaryMatrixRoute
  ReferenceSephirothicMatrixRoute: typeof ReferenceSephirothicMatrixRoute
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute
  SettingsArtRoute: typeof SettingsArtRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsManualRoute: typeof SettingsManualRoute
  SettingsNavRoute: typeof SettingsNavRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTraditionsRoute: typeof SettingsTraditionsRoute
  StudySessionRoute: typeof StudySessionRoute
  StudySettingsRoute: typeof StudySettingsRoute
  AstrologyIndexRoute: typeof AstrologyIndexRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CustomIndexRoute: typeof CustomIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  QabalahIndexRoute: typeof QabalahIndexRoute
  ReadIndexRoute: typeof ReadIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qabalah/': {
      id: '/qabalah/'
      path: '/qabalah'
      fullPath: '/qabalah/'
      preLoaderRoute: typeof QabalahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/': {
      id: '/custom/'
      path: '/custom'
      fullPath: '/custom/'
      preLoaderRoute: typeof CustomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/': {
      id: '/astrology/'
      path: '/astrology'
      fullPath: '/astrology/'
      preLoaderRoute: typeof AstrologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/settings': {
      id: '/study/settings'
      path: '/study/settings'
      fullPath: '/study/settings'
      preLoaderRoute: typeof StudySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/session': {
      id: '/study/session'
      path: '/study/session'
      fullPath: '/study/session'
      preLoaderRoute: typeof StudySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/traditions': {
      id: '/settings/traditions'
      path: '/settings/traditions'
      fullPath: '/settings/traditions'
      preLoaderRoute: typeof SettingsTraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/nav': {
      id: '/settings/nav'
      path: '/settings/nav'
      fullPath: '/settings/nav'
      preLoaderRoute: typeof SettingsNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/manual': {
      id: '/settings/manual'
      path: '/settings/manual'
      fullPath: '/settings/manual'
      preLoaderRoute: typeof SettingsManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/art': {
      id: '/settings/art'
      path: '/settings/art'
      fullPath: '/settings/art'
      preLoaderRoute: typeof SettingsArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/accessibility': {
      id: '/settings/accessibility'
      path: '/settings/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof SettingsAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/sephirothic-matrix': {
      id: '/reference/sephirothic-matrix'
      path: '/reference/sephirothic-matrix'
      fullPath: '/reference/sephirothic-matrix'
      preLoaderRoute: typeof ReferenceSephirothicMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/planetary-matrix': {
      id: '/reference/planetary-matrix'
      path: '/reference/planetary-matrix'
      fullPath: '/reference/planetary-matrix'
      preLoaderRoute: typeof ReferencePlanetaryMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/lenormand-combinations': {
      id: '/reference/lenormand-combinations'
      path: '/reference/lenormand-combinations'
      fullPath: '/reference/lenormand-combinations'
      preLoaderRoute: typeof ReferenceLenormandCombinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/iching-trigram-matrix': {
      id: '/reference/iching-trigram-matrix'
      path: '/reference/iching-trigram-matrix'
      fullPath: '/reference/iching-trigram-matrix'
      preLoaderRoute: typeof ReferenceIchingTrigramMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/geomancy-shield-chart': {
      id: '/reference/geomancy-shield-chart'
      path: '/reference/geomancy-shield-chart'
      fullPath: '/reference/geomancy-shield-chart'
      preLoaderRoute: typeof ReferenceGeomancyShieldChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/chinese-zodiac-compatibility': {
      id: '/reference/chinese-zodiac-compatibility'
      path: '/reference/chinese-zodiac-compatibility'
      fullPath: '/reference/chinese-zodiac-compatibility'
      preLoaderRoute: typeof ReferenceChineseZodiacCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/astrological-dignities': {
      id: '/reference/astrological-dignities'
      path: '/reference/astrological-dignities'
      fullPath: '/reference/astrological-dignities'
      preLoaderRoute: typeof ReferenceAstrologicalDignitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/$canonicalName': {
      id: '/reference/$canonicalName'
      path: '/reference/$canonicalName'
      fullPath: '/reference/$canonicalName'
      preLoaderRoute: typeof ReferenceCanonicalNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/spreads': {
      id: '/read/spreads'
      path: '/read/spreads'
      fullPath: '/read/spreads'
      preLoaderRoute: typeof ReadSpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/record': {
      id: '/read/record'
      path: '/read/record'
      fullPath: '/read/record'
      preLoaderRoute: typeof ReadRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/draw': {
      id: '/read/draw'
      path: '/read/draw'
      fullPath: '/read/draw'
      preLoaderRoute: typeof ReadDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/decks': {
      id: '/read/decks'
      path: '/read/decks'
      fullPath: '/read/decks'
      preLoaderRoute: typeof ReadDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qabalah/numerology': {
      id: '/qabalah/numerology'
      path: '/qabalah/numerology'
      fullPath: '/qabalah/numerology'
      preLoaderRoute: typeof QabalahNumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qabalah/gematria': {
      id: '/qabalah/gematria'
      path: '/qabalah/gematria'
      fullPath: '/qabalah/gematria'
      preLoaderRoute: typeof QabalahGematriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/stats': {
      id: '/journal/stats'
      path: '/journal/stats'
      fullPath: '/journal/stats'
      preLoaderRoute: typeof JournalStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/traditions': {
      id: '/custom/traditions'
      path: '/custom/traditions'
      fullPath: '/custom/traditions'
      preLoaderRoute: typeof CustomTraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/new': {
      id: '/custom/new'
      path: '/custom/new'
      fullPath: '/custom/new'
      preLoaderRoute: typeof CustomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$cn': {
      id: '/custom/$cn'
      path: '/custom/$cn'
      fullPath: '/custom/$cn'
      preLoaderRoute: typeof CustomCnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/new': {
      id: '/astrology/new'
      path: '/astrology/new'
      fullPath: '/astrology/new'
      preLoaderRoute: typeof AstrologyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/animate': {
      id: '/astrology/animate'
      path: '/astrology/animate'
      fullPath: '/astrology/animate'
      preLoaderRoute: typeof AstrologyAnimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/$id': {
      id: '/astrology/$id'
      path: '/astrology/$id'
      fullPath: '/astrology/$id'
      preLoaderRoute: typeof AstrologyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologyIdRoute: AstrologyIdRoute,
  AstrologyAnimateRoute: AstrologyAnimateRoute,
  AstrologyNewRoute: AstrologyNewRoute,
  CustomCnRoute: CustomCnRoute,
  CustomNewRoute: CustomNewRoute,
  CustomTraditionsRoute: CustomTraditionsRoute,
  JournalStatsRoute: JournalStatsRoute,
  QabalahGematriaRoute: QabalahGematriaRoute,
  QabalahNumerologyRoute: QabalahNumerologyRoute,
  ReadDecksRoute: ReadDecksRoute,
  ReadDrawRoute: ReadDrawRoute,
  ReadRecordRoute: ReadRecordRoute,
  ReadSpreadsRoute: ReadSpreadsRoute,
  ReferenceCanonicalNameRoute: ReferenceCanonicalNameRoute,
  ReferenceAstrologicalDignitiesRoute: ReferenceAstrologicalDignitiesRoute,
  ReferenceChineseZodiacCompatibilityRoute:
    ReferenceChineseZodiacCompatibilityRoute,
  ReferenceGeomancyShieldChartRoute: ReferenceGeomancyShieldChartRoute,
  ReferenceIchingTrigramMatrixRoute: ReferenceIchingTrigramMatrixRoute,
  ReferenceLenormandCombinationsRoute: ReferenceLenormandCombinationsRoute,
  ReferencePlanetaryMatrixRoute: ReferencePlanetaryMatrixRoute,
  ReferenceSephirothicMatrixRoute: ReferenceSephirothicMatrixRoute,
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
  SettingsArtRoute: SettingsArtRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsManualRoute: SettingsManualRoute,
  SettingsNavRoute: SettingsNavRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTraditionsRoute: SettingsTraditionsRoute,
  StudySessionRoute: StudySessionRoute,
  StudySettingsRoute: StudySettingsRoute,
  AstrologyIndexRoute: AstrologyIndexRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CustomIndexRoute: CustomIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  QabalahIndexRoute: QabalahIndexRoute,
  ReadIndexRoute: ReadIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
