import type { ConstellationDiagramData } from '@/components/ui/ConstellationDiagram'

/**
 * Schematic star-chart layouts for each constellation entity page.
 * Coordinates are illustrative (recognisable traditional asterism shapes),
 * not precise sky projections. Only stars with a canonicalName have their
 * own astrology.fixed-star.* entity page and render as labelled, clickable
 * points; the rest are anonymous unlabelled points included only to complete
 * the traditional outline.
 */
export const CONSTELLATION_DIAGRAMS: Record<string, ConstellationDiagramData> = {
  'aries': {
    viewBox: '0 0 260 220',
    stars: [
      { id: 'mesarthim', x: 70, y: 170, mag: 3, canonicalName: 'astrology.fixed-star.mesarthim', label: 'Mesarthim' },
      { id: 'sheratan', x: 130, y: 120, mag: 2, canonicalName: 'astrology.fixed-star.sheratan', label: 'Sheratan' },
      { id: 'hamal', x: 200, y: 60, mag: 1, canonicalName: 'astrology.fixed-star.hamal', label: 'Hamal' },
      { id: 'botein', x: 220, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.botein', label: 'Botein' },
    ],
    lines: [
      ['mesarthim', 'sheratan'],
      ['sheratan', 'hamal'],
      ['hamal', 'botein'],
    ],
  },
  'andromeda': {
    viewBox: '0 0 330 220',
    stars: [
      { id: 'alpheratz', x: 50, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.alpheratz', label: 'Alpheratz' },
      { id: 'mirach', x: 150, y: 140, mag: 2, canonicalName: 'astrology.fixed-star.mirach', label: 'Mirach' },
      { id: 'almach', x: 260, y: 70, mag: 2, canonicalName: 'astrology.fixed-star.almach', label: 'Almach' },
    ],
    lines: [
      ['alpheratz', 'mirach'],
      ['mirach', 'almach'],
    ],
  },
  'taurus': {
    viewBox: '0 0 300 220',
    stars: [
      { id: 'pleiades', x: 210, y: 40, mag: 2, canonicalName: 'astrology.fixed-star.alcyone', label: 'Alcyone' },
      { id: 'nose', x: 150, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.prima-hyadum', label: 'Prima Hyadum' },
      { id: 'aldebaran', x: 110, y: 120, mag: 1, canonicalName: 'astrology.fixed-star.aldebaran', label: 'Aldebaran' },
      { id: 'horn_left', x: 60, y: 50, mag: 3, canonicalName: 'astrology.fixed-star.ain', label: 'Ain' },
      { id: 'face_right', x: 200, y: 140, mag: 4, canonicalName: 'astrology.fixed-star.secunda-hyadum', label: 'Secunda Hyadum' },
      { id: 'alnath', x: 250, y: 60, mag: 2, canonicalName: 'astrology.fixed-star.alnath', label: 'Alnath' },
    ],
    lines: [
      ['nose', 'aldebaran'],
      ['aldebaran', 'horn_left'],
      ['nose', 'face_right'],
      ['face_right', 'alnath'],
    ],
  },
  'orion': {
    viewBox: '0 0 320 340',
    stars: [
      { id: 'betelgeuse', x: 80, y: 60, mag: 1, canonicalName: 'astrology.fixed-star.betelgeuse', label: 'Betelgeuse' },
      { id: 'bellatrix', x: 220, y: 70, mag: 2, canonicalName: 'astrology.fixed-star.bellatrix', label: 'Bellatrix' },
      { id: 'mintaka', x: 140, y: 160, mag: 2, canonicalName: 'astrology.fixed-star.mintaka', label: 'Mintaka' },
      { id: 'alnilam', x: 170, y: 170, mag: 1, canonicalName: 'astrology.fixed-star.alnilam', label: 'Alnilam' },
      { id: 'alnitak', x: 200, y: 180, mag: 2, canonicalName: 'astrology.fixed-star.alnitak', label: 'Alnitak' },
      { id: 'saiph', x: 100, y: 300, mag: 3, canonicalName: 'astrology.fixed-star.saiph', label: 'Saiph' },
      { id: 'rigel', x: 240, y: 290, mag: 1, canonicalName: 'astrology.fixed-star.rigel', label: 'Rigel' },
      { id: 'meissa', x: 150, y: 20, mag: 4, canonicalName: 'astrology.fixed-star.meissa', label: 'Meissa' },
    ],
    lines: [
      ['betelgeuse', 'mintaka'],
      ['bellatrix', 'alnitak'],
      ['mintaka', 'alnilam'],
      ['alnilam', 'alnitak'],
      ['mintaka', 'saiph'],
      ['alnitak', 'rigel'],
      ['betelgeuse', 'meissa'],
      ['meissa', 'bellatrix'],
    ],
  },
  'auriga': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'capella', x: 150, y: 50, mag: 1, canonicalName: 'astrology.fixed-star.capella', label: 'Capella' },
      { id: 'p2', x: 230, y: 110, mag: 3, canonicalName: 'astrology.fixed-star.menkalinan', label: 'Menkalinan' },
      { id: 'p3', x: 210, y: 210, mag: 3 },
      { id: 'p4', x: 90, y: 210, mag: 3 },
      { id: 'p5', x: 70, y: 110, mag: 3, canonicalName: 'astrology.fixed-star.hassaleh', label: 'Hassaleh' },
    ],
    lines: [
      ['capella', 'p2'],
      ['p2', 'p3'],
      ['p3', 'p4'],
      ['p4', 'p5'],
      ['p5', 'capella'],
    ],
  },
  'bootes': {
    viewBox: '0 0 320 280',
    stars: [
      { id: 'arcturus', x: 150, y: 260, mag: 1, canonicalName: 'astrology.fixed-star.arcturus', label: 'Arcturus' },
      { id: 'left', x: 90, y: 150, mag: 3, canonicalName: 'astrology.fixed-star.izar', label: 'Izar' },
      { id: 'top', x: 140, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.seginus', label: 'Seginus' },
      { id: 'right', x: 210, y: 110, mag: 3, canonicalName: 'astrology.fixed-star.nekkar', label: 'Nekkar' },
      { id: 'lowerright', x: 190, y: 190, mag: 3, canonicalName: 'astrology.fixed-star.muphrid', label: 'Muphrid' },
      { id: 'alkalurops', x: 240, y: 60, mag: 4, canonicalName: 'astrology.fixed-star.alkalurops', label: 'Alkalurops' },
    ],
    lines: [
      ['arcturus', 'left'],
      ['left', 'top'],
      ['top', 'right'],
      ['right', 'lowerright'],
      ['right', 'alkalurops'],
      ['lowerright', 'arcturus'],
    ],
  },
  'cancer': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'north_asellus', x: 120, y: 80, mag: 3, canonicalName: 'astrology.fixed-star.north-asellus', label: 'North Asellus' },
      { id: 'south_asellus', x: 180, y: 80, mag: 3, canonicalName: 'astrology.fixed-star.south-asellus', label: 'South Asellus' },
      { id: 'praesepe', x: 150, y: 130, mag: 3, canonicalName: 'astrology.fixed-star.praesepe', label: 'Praesepe' },
      { id: 'tail', x: 150, y: 230, mag: 4, canonicalName: 'astrology.fixed-star.acubens', label: 'Acubens' },
    ],
    lines: [
      ['north_asellus', 'praesepe'],
      ['south_asellus', 'praesepe'],
      ['praesepe', 'tail'],
    ],
  },
  'canis-major': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'head', x: 90, y: 50, mag: 3, canonicalName: 'astrology.fixed-star.mirzam', label: 'Mirzam' },
      { id: 'sirius', x: 150, y: 80, mag: 1, canonicalName: 'astrology.fixed-star.sirius', label: 'Sirius' },
      { id: 'chest', x: 150, y: 150, mag: 3, canonicalName: 'astrology.fixed-star.wezen', label: 'Wezen' },
      { id: 'front_leg', x: 110, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.muliphein', label: 'Muliphein' },
      { id: 'back_leg', x: 210, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.adhara', label: 'Adhara' },
      { id: 'tail', x: 250, y: 140, mag: 3, canonicalName: 'astrology.fixed-star.aludra', label: 'Aludra' },
      { id: 'furud', x: 200, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.furud', label: 'Furud' },
    ],
    lines: [
      ['head', 'sirius'],
      ['sirius', 'chest'],
      ['chest', 'front_leg'],
      ['chest', 'back_leg'],
      ['chest', 'tail'],
      ['sirius', 'furud'],
    ],
  },
  'canis-minor': {
    viewBox: '0 0 260 220',
    stars: [
      { id: 'procyon', x: 180, y: 150, mag: 1, canonicalName: 'astrology.fixed-star.procyon', label: 'Procyon' },
      { id: 'gomeisa', x: 90, y: 90, mag: 3, canonicalName: 'astrology.fixed-star.gomeisa', label: 'Gomeisa' },
    ],
    lines: [
      ['procyon', 'gomeisa'],
    ],
  },
  'capricornus': {
    viewBox: '0 0 350 220',
    stars: [
      { id: 'algedi', x: 60, y: 80, mag: 3, canonicalName: 'astrology.fixed-star.algedi', label: 'Algedi' },
      { id: 'dabih', x: 100, y: 140, mag: 3, canonicalName: 'astrology.fixed-star.dabih', label: 'Dabih' },
      { id: 'nashira', x: 200, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.nashira', label: 'Nashira' },
      { id: 'deneb_algedi', x: 260, y: 160, mag: 2, canonicalName: 'astrology.fixed-star.deneb-algedi', label: 'Deneb Algedi' },
      { id: 'alshat', x: 40, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.alshat', label: 'Alshat' },
      { id: 'baten_algiedi', x: 150, y: 140, mag: 4, canonicalName: 'astrology.fixed-star.baten-algiedi', label: 'Baten Algiedi' },
    ],
    lines: [
      ['algedi', 'dabih'],
      ['dabih', 'nashira'],
      ['nashira', 'deneb_algedi'],
      ['algedi', 'alshat'],
      ['dabih', 'baten_algiedi'],
    ],
  },
  'carina': {
    viewBox: '0 0 300 240',
    stars: [
      { id: 'canopus', x: 150, y: 200, mag: 1, canonicalName: 'astrology.fixed-star.canopus', label: 'Canopus' },
      { id: 'miaplacidus', x: 80, y: 100, mag: 3, canonicalName: 'astrology.fixed-star.miaplacidus', label: 'Miaplacidus' },
      { id: 'avior', x: 230, y: 120, mag: 3, canonicalName: 'astrology.fixed-star.avior', label: 'Avior' },
      { id: 'aspidiske', x: 190, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.aspidiske', label: 'Aspidiske' },
    ],
    lines: [
      ['canopus', 'miaplacidus'],
      ['canopus', 'avior'],
      ['avior', 'aspidiske'],
    ],
  },
  'centaurus': {
    viewBox: '0 0 360 260',
    stars: [
      { id: 'alpha_cen', x: 220, y: 100, mag: 1, canonicalName: 'astrology.fixed-star.rigil-kentaurus', label: 'Rigil Kentaurus' },
      { id: 'agena', x: 150, y: 110, mag: 1, canonicalName: 'astrology.fixed-star.agena', label: 'Agena' },
      { id: 'menkent', x: 80, y: 180, mag: 3, canonicalName: 'astrology.fixed-star.menkent', label: 'Menkent' },
      { id: 'body1', x: 160, y: 200, mag: 4, canonicalName: 'astrology.fixed-star.muhlifain', label: 'Muhlifain' },
      { id: 'body2', x: 230, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.epsilon-centauri', label: 'Epsilon Centauri' },
      { id: 'zeta_cen', x: 270, y: 170, mag: 4, canonicalName: 'astrology.fixed-star.zeta-centauri', label: 'Zeta Centauri' },
      { id: 'eta_cen', x: 190, y: 150, mag: 4, canonicalName: 'astrology.fixed-star.eta-centauri', label: 'Eta Centauri' },
    ],
    lines: [
      ['alpha_cen', 'agena'],
      ['agena', 'menkent'],
      ['agena', 'body1'],
      ['body1', 'body2'],
      ['body2', 'zeta_cen'],
      ['agena', 'eta_cen'],
    ],
  },
  'corvus': {
    viewBox: '0 0 300 240',
    stars: [
      { id: 'gienah', x: 90, y: 70, mag: 3, canonicalName: 'astrology.fixed-star.gienah', label: 'Gienah' },
      { id: 'algorab', x: 210, y: 70, mag: 2, canonicalName: 'astrology.fixed-star.algorab', label: 'Algorab' },
      { id: 'kraz', x: 200, y: 180, mag: 3, canonicalName: 'astrology.fixed-star.kraz', label: 'Kraz' },
      { id: 'minkar', x: 100, y: 170, mag: 3, canonicalName: 'astrology.fixed-star.minkar', label: 'Minkar' },
    ],
    lines: [
      ['gienah', 'algorab'],
      ['algorab', 'kraz'],
      ['kraz', 'minkar'],
      ['minkar', 'gienah'],
    ],
  },
  'cygnus': {
    viewBox: '0 0 350 280',
    stars: [
      { id: 'deneb', x: 150, y: 50, mag: 1, canonicalName: 'astrology.fixed-star.deneb', label: 'Deneb' },
      { id: 'sadr', x: 150, y: 130, mag: 3, canonicalName: 'astrology.fixed-star.sadr', label: 'Sadr' },
      { id: 'albireo', x: 150, y: 240, mag: 3, canonicalName: 'astrology.fixed-star.albireo', label: 'Albireo' },
      { id: 'wing_left', x: 70, y: 130, mag: 3, canonicalName: 'astrology.fixed-star.fawaris', label: 'Fawaris' },
      { id: 'wing_right', x: 230, y: 130, mag: 3, canonicalName: 'astrology.fixed-star.gienah-cygni', label: 'Gienah Cygni' },
      { id: 'zeta_cyg', x: 260, y: 90, mag: 4, canonicalName: 'astrology.fixed-star.zeta-cygni', label: 'Zeta Cygni' },
    ],
    lines: [
      ['deneb', 'sadr'],
      ['sadr', 'albireo'],
      ['wing_left', 'sadr'],
      ['sadr', 'wing_right'],
      ['wing_right', 'zeta_cyg'],
    ],
  },
  'draco': {
    viewBox: '0 0 300 300',
    stars: [
      { id: 'eltanin', x: 200, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.eltanin', label: 'Eltanin' },
      { id: 'rastaban', x: 150, y: 50, mag: 2, canonicalName: 'astrology.fixed-star.rastaban', label: 'Rastaban' },
      { id: 'grumium', x: 140, y: 90, mag: 4, canonicalName: 'astrology.fixed-star.grumium', label: 'Grumium' },
      { id: 'head4', x: 190, y: 100, mag: 4, canonicalName: 'astrology.fixed-star.edasich', label: 'Edasich' },
      { id: 'tail1', x: 100, y: 140, mag: 4, canonicalName: 'astrology.fixed-star.aldhibah', label: 'Aldhibah' },
      { id: 'tail2', x: 60, y: 200, mag: 4, canonicalName: 'astrology.fixed-star.thuban', label: 'Thuban' },
      { id: 'tail3', x: 90, y: 260, mag: 4, canonicalName: 'astrology.fixed-star.altais', label: 'Altais' },
      { id: 'tail4', x: 160, y: 280, mag: 4, canonicalName: 'astrology.fixed-star.athebyne', label: 'Athebyne' },
    ],
    lines: [
      ['eltanin', 'rastaban'],
      ['rastaban', 'grumium'],
      ['grumium', 'head4'],
      ['head4', 'eltanin'],
      ['grumium', 'tail1'],
      ['tail1', 'tail2'],
      ['tail2', 'tail3'],
      ['tail3', 'tail4'],
    ],
  },
  'eridanus': {
    viewBox: '0 0 260 320',
    stars: [
      { id: 'cursa', x: 150, y: 20, mag: 3, canonicalName: 'astrology.fixed-star.cursa', label: 'Cursa' },
      { id: 'p2', x: 100, y: 70, mag: 4, canonicalName: 'astrology.fixed-star.zaurak', label: 'Zaurak' },
      { id: 'p3', x: 140, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.beid', label: 'Beid' },
      { id: 'p4', x: 90, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.keid', label: 'Keid' },
      { id: 'p5', x: 130, y: 250, mag: 4, canonicalName: 'astrology.fixed-star.acamar', label: 'Acamar' },
      { id: 'achernar', x: 150, y: 310, mag: 1, canonicalName: 'astrology.fixed-star.achernar', label: 'Achernar' },
      { id: 'rana', x: 60, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.rana', label: 'Rana' },
      { id: 'azha', x: 190, y: 210, mag: 4, canonicalName: 'astrology.fixed-star.azha', label: 'Azha' },
    ],
    lines: [
      ['cursa', 'p2'],
      ['p2', 'p3'],
      ['p3', 'p4'],
      ['p4', 'p5'],
      ['p5', 'achernar'],
      ['p3', 'rana'],
      ['p4', 'azha'],
    ],
  },
  'gemini': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'castor', x: 110, y: 50, mag: 1, canonicalName: 'astrology.fixed-star.castor', label: 'Castor' },
      { id: 'pollux', x: 210, y: 60, mag: 1, canonicalName: 'astrology.fixed-star.pollux', label: 'Pollux' },
      { id: 'castor_foot', x: 90, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.mebsuta', label: 'Mebsuta' },
      { id: 'pollux_foot', x: 230, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.alhena', label: 'Alhena' },
      { id: 'wasat', x: 165, y: 140, mag: 4, canonicalName: 'astrology.fixed-star.wasat', label: 'Wasat' },
      { id: 'propus', x: 100, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.propus', label: 'Propus' },
    ],
    lines: [
      ['castor', 'pollux'],
      ['castor', 'castor_foot'],
      ['pollux', 'pollux_foot'],
      ['castor_foot', 'wasat'],
      ['wasat', 'pollux_foot'],
      ['castor', 'propus'],
    ],
  },
  'hercules': {
    viewBox: '0 0 300 280',
    stars: [
      { id: 'k1', x: 150, y: 80, mag: 3, canonicalName: 'astrology.fixed-star.kajam', label: 'Kajam' },
      { id: 'k2', x: 200, y: 110, mag: 3, canonicalName: 'astrology.fixed-star.kornephoros', label: 'Kornephoros' },
      { id: 'k3', x: 190, y: 170, mag: 3, canonicalName: 'astrology.fixed-star.marsic', label: 'Marsic' },
      { id: 'k4', x: 130, y: 160, mag: 3, canonicalName: 'astrology.fixed-star.maasym', label: 'Maasym' },
      { id: 'ras_algethi', x: 100, y: 240, mag: 2, canonicalName: 'astrology.fixed-star.ras-algethi', label: 'Ras Algethi' },
      { id: 'limb_end', x: 230, y: 230, mag: 4, canonicalName: 'astrology.fixed-star.sarin', label: 'Sarin' },
    ],
    lines: [
      ['k1', 'k2'],
      ['k2', 'k3'],
      ['k3', 'k4'],
      ['k4', 'k1'],
      ['k4', 'ras_algethi'],
      ['k2', 'limb_end'],
    ],
  },
  'hydra': {
    viewBox: '0 0 260 340',
    stars: [
      { id: 'head1', x: 60, y: 40, mag: 4 },
      { id: 'head2', x: 90, y: 50, mag: 4 },
      { id: 'neck', x: 120, y: 90, mag: 4, canonicalName: 'astrology.fixed-star.zeta-hydrae', label: 'Zeta Hydrae' },
      { id: 'alphard', x: 160, y: 140, mag: 1, canonicalName: 'astrology.fixed-star.alphard', label: 'Alphard' },
      { id: 'b1', x: 200, y: 180, mag: 4, canonicalName: 'astrology.fixed-star.ukdah', label: 'Ukdah' },
      { id: 'b2', x: 170, y: 230, mag: 4, canonicalName: 'astrology.fixed-star.xi-hydrae', label: 'Xi Hydrae' },
      { id: 'b3', x: 220, y: 270, mag: 4 },
      { id: 'b4', x: 180, y: 310, mag: 4, canonicalName: 'astrology.fixed-star.beta-hydrae', label: 'Beta Hydrae' },
    ],
    lines: [
      ['head1', 'head2'],
      ['head2', 'neck'],
      ['neck', 'alphard'],
      ['alphard', 'b1'],
      ['b1', 'b2'],
      ['b2', 'b3'],
      ['b3', 'b4'],
    ],
  },
  'leo': {
    viewBox: '0 0 360 260',
    stars: [
      { id: 's4', x: 190, y: 80, mag: 3 },
      { id: 's3', x: 150, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.adhafera', label: 'Adhafera' },
      { id: 's2', x: 110, y: 100, mag: 3, canonicalName: 'astrology.fixed-star.algieba', label: 'Algieba' },
      { id: 's1', x: 90, y: 160, mag: 3 },
      { id: 'regulus', x: 100, y: 220, mag: 1, canonicalName: 'astrology.fixed-star.regulus', label: 'Regulus' },
      { id: 'zosma', x: 230, y: 150, mag: 2, canonicalName: 'astrology.fixed-star.zosma', label: 'Zosma' },
      { id: 'denebola', x: 290, y: 180, mag: 1, canonicalName: 'astrology.fixed-star.denebola', label: 'Denebola' },
      { id: 'tri3', x: 240, y: 220, mag: 4 },
    ],
    lines: [
      ['regulus', 's1'],
      ['s1', 's2'],
      ['s2', 's3'],
      ['s3', 's4'],
      ['regulus', 'zosma'],
      ['zosma', 'denebola'],
      ['denebola', 'tri3'],
      ['tri3', 'regulus'],
    ],
  },
  'libra': {
    viewBox: '0 0 380 240',
    stars: [
      { id: 'zubenelgenubi', x: 90, y: 180, mag: 2, canonicalName: 'astrology.fixed-star.zubenelgenubi', label: 'Zubenelgenubi' },
      { id: 'zubeneschamali', x: 230, y: 150, mag: 2, canonicalName: 'astrology.fixed-star.zubeneschamali', label: 'Zubeneschamali' },
      { id: 'brachium', x: 160, y: 80, mag: 4, canonicalName: 'astrology.fixed-star.brachium', label: 'Brachium' },
      { id: 'zubenelhakrabi', x: 270, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.zubenelhakrabi', label: 'Zubenelhakrabi' },
    ],
    lines: [
      ['zubenelgenubi', 'brachium'],
      ['brachium', 'zubeneschamali'],
      ['zubenelgenubi', 'zubeneschamali'],
      ['zubeneschamali', 'zubenelhakrabi'],
    ],
  },
  'lyra': {
    viewBox: '0 0 260 220',
    stars: [
      { id: 'vega', x: 120, y: 40, mag: 1, canonicalName: 'astrology.fixed-star.vega', label: 'Vega' },
      { id: 'q1', x: 90, y: 110, mag: 3, canonicalName: 'astrology.fixed-star.zeta-lyrae', label: 'Zeta Lyrae' },
      { id: 'q2', x: 160, y: 100, mag: 3 },
      { id: 'q3', x: 175, y: 170, mag: 3, canonicalName: 'astrology.fixed-star.sulafat', label: 'Sulafat' },
      { id: 'q4', x: 105, y: 180, mag: 3, canonicalName: 'astrology.fixed-star.sheliak', label: 'Sheliak' },
    ],
    lines: [
      ['vega', 'q1'],
      ['q1', 'q2'],
      ['q2', 'q3'],
      ['q3', 'q4'],
      ['q4', 'q1'],
    ],
  },
  'ophiuchus': {
    viewBox: '0 0 360 300',
    stars: [
      { id: 'rasalhague', x: 150, y: 40, mag: 2, canonicalName: 'astrology.fixed-star.rasalhague', label: 'Rasalhague' },
      { id: 'shoulder_l', x: 90, y: 100, mag: 3, canonicalName: 'astrology.fixed-star.cebalrai', label: 'Cebalrai' },
      { id: 'shoulder_r', x: 210, y: 100, mag: 3 },
      { id: 'hip_l', x: 100, y: 220, mag: 3 },
      { id: 'hip_r', x: 200, y: 220, mag: 3 },
      { id: 'sabik', x: 230, y: 270, mag: 2, canonicalName: 'astrology.fixed-star.sabik', label: 'Sabik' },
      { id: 'other_foot', x: 70, y: 270, mag: 4 },
      { id: 'yed_prior', x: 250, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.yed-prior', label: 'Yed Prior' },
      { id: 'yed_posterior', x: 270, y: 150, mag: 4, canonicalName: 'astrology.fixed-star.yed-posterior', label: 'Yed Posterior' },
    ],
    lines: [
      ['rasalhague', 'shoulder_l'],
      ['rasalhague', 'shoulder_r'],
      ['shoulder_l', 'hip_l'],
      ['shoulder_r', 'hip_r'],
      ['hip_l', 'other_foot'],
      ['hip_r', 'sabik'],
      ['shoulder_r', 'yed_prior'],
      ['yed_prior', 'yed_posterior'],
    ],
  },
  'pegasus': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'scheat', x: 90, y: 60, mag: 2, canonicalName: 'astrology.fixed-star.scheat', label: 'Scheat' },
      { id: 'alpheratz', x: 230, y: 60, mag: 3, canonicalName: 'astrology.fixed-star.alpheratz', label: 'Alpheratz' },
      { id: 'algenib', x: 230, y: 200, mag: 3, canonicalName: 'astrology.fixed-star.algenib', label: 'Algenib' },
      { id: 'markab', x: 90, y: 200, mag: 2, canonicalName: 'astrology.fixed-star.markab', label: 'Markab' },
      { id: 'enif', x: 20, y: 230, mag: 2, canonicalName: 'astrology.fixed-star.enif', label: 'Enif' },
      { id: 'biham', x: 60, y: 210, mag: 4, canonicalName: 'astrology.fixed-star.biham', label: 'Biham' },
      { id: 'homam', x: 40, y: 250, mag: 4, canonicalName: 'astrology.fixed-star.homam', label: 'Homam' },
    ],
    lines: [
      ['scheat', 'alpheratz'],
      ['alpheratz', 'algenib'],
      ['algenib', 'markab'],
      ['markab', 'scheat'],
      ['markab', 'biham'],
      ['biham', 'homam'],
      ['homam', 'enif'],
    ],
  },
  'piscis-austrinus': {
    viewBox: '0 0 300 260',
    stars: [
      { id: 'l3', x: 140, y: 60, mag: 4, canonicalName: 'astrology.fixed-star.epsilon-piscis-austrini', label: 'Epsilon Piscis Austrini' },
      { id: 'l4', x: 200, y: 70, mag: 4 },
      { id: 'l2', x: 90, y: 100, mag: 4 },
      { id: 'l5', x: 230, y: 120, mag: 4 },
      { id: 'l1', x: 100, y: 160, mag: 4 },
      { id: 'l6', x: 220, y: 180, mag: 4 },
      { id: 'fomalhaut', x: 150, y: 220, mag: 1, canonicalName: 'astrology.fixed-star.fomalhaut', label: 'Fomalhaut' },
    ],
    lines: [
      ['l3', 'l4'],
      ['l4', 'l5'],
      ['l5', 'l6'],
      ['l6', 'fomalhaut'],
      ['fomalhaut', 'l1'],
      ['l1', 'l2'],
      ['l2', 'l3'],
    ],
  },
  'scorpius': {
    viewBox: '0 0 320 320',
    stars: [
      { id: 'h1', x: 150, y: 40, mag: 4, canonicalName: 'astrology.fixed-star.dschubba', label: 'Dschubba' },
      { id: 'h2', x: 120, y: 60, mag: 4, canonicalName: 'astrology.fixed-star.jabbah', label: 'Jabbah' },
      { id: 'h3', x: 180, y: 60, mag: 4, canonicalName: 'astrology.fixed-star.graffias', label: 'Graffias' },
      { id: 'antares', x: 150, y: 110, mag: 1, canonicalName: 'astrology.fixed-star.antares', label: 'Antares' },
      { id: 'body1', x: 160, y: 170, mag: 3, canonicalName: 'astrology.fixed-star.alniyat', label: 'Alniyat' },
      { id: 'body2', x: 140, y: 220, mag: 3 },
      { id: 'curve1', x: 180, y: 260, mag: 3, canonicalName: 'astrology.fixed-star.sargas', label: 'Sargas' },
      { id: 'curve2', x: 230, y: 280, mag: 3, canonicalName: 'astrology.fixed-star.lesath', label: 'Lesath' },
      { id: 'stinger', x: 260, y: 240, mag: 3, canonicalName: 'astrology.fixed-star.shaula', label: 'Shaula' },
    ],
    lines: [
      ['h2', 'h1'],
      ['h1', 'h3'],
      ['h1', 'antares'],
      ['antares', 'body1'],
      ['body1', 'body2'],
      ['body2', 'curve1'],
      ['curve1', 'curve2'],
      ['curve2', 'stinger'],
    ],
  },
  'serpens': {
    viewBox: '0 0 260 320',
    stars: [
      { id: 'head1', x: 70, y: 30, mag: 4, canonicalName: 'astrology.fixed-star.beta-serpentis', label: 'Beta Serpentis' },
      { id: 'head2', x: 100, y: 75, mag: 4, canonicalName: 'astrology.fixed-star.mu-serpentis', label: 'Mu Serpentis' },
      { id: 'unukalhai', x: 140, y: 110, mag: 2, canonicalName: 'astrology.fixed-star.unukalhai', label: 'Unukalhai' },
      { id: 'body1', x: 180, y: 180, mag: 4 },
      { id: 'body2', x: 160, y: 250, mag: 4 },
      { id: 'alya', x: 130, y: 300, mag: 4, canonicalName: 'astrology.fixed-star.alya', label: 'Alya' },
    ],
    lines: [
      ['head1', 'head2'],
      ['head1', 'unukalhai'],
      ['head2', 'unukalhai'],
      ['unukalhai', 'body1'],
      ['body1', 'body2'],
      ['body2', 'alya'],
    ],
  },
  'ursa-minor': {
    viewBox: '0 0 300 220',
    stars: [
      { id: 'polaris', x: 50, y: 50, mag: 1, canonicalName: 'astrology.fixed-star.polaris', label: 'Polaris' },
      { id: 'h1', x: 110, y: 70, mag: 3 },
      { id: 'h2', x: 160, y: 100, mag: 3 },
      { id: 'bowl1', x: 220, y: 90, mag: 3 },
      { id: 'bowl2', x: 260, y: 140, mag: 3, canonicalName: 'astrology.fixed-star.kochab', label: 'Kochab' },
      { id: 'bowl3', x: 230, y: 190, mag: 3, canonicalName: 'astrology.fixed-star.pherkad', label: 'Pherkad' },
      { id: 'bowl4', x: 180, y: 160, mag: 3 },
    ],
    lines: [
      ['polaris', 'h1'],
      ['h1', 'h2'],
      ['h2', 'bowl1'],
      ['bowl1', 'bowl2'],
      ['bowl2', 'bowl3'],
      ['bowl3', 'bowl4'],
      ['bowl4', 'bowl1'],
    ],
  },
  'virgo': {
    viewBox: '0 0 300 300',
    stars: [
      { id: 'head', x: 150, y: 40, mag: 4, canonicalName: 'astrology.fixed-star.porrima', label: 'Porrima' },
      { id: 'vindemiatrix', x: 220, y: 80, mag: 3, canonicalName: 'astrology.fixed-star.vindemiatrix', label: 'Vindemiatrix' },
      { id: 'wing_left', x: 80, y: 90, mag: 4, canonicalName: 'astrology.fixed-star.zavijava', label: 'Zavijava' },
      { id: 'waist', x: 150, y: 150, mag: 4, canonicalName: 'astrology.fixed-star.auva', label: 'Auva' },
      { id: 'spica', x: 170, y: 260, mag: 1, canonicalName: 'astrology.fixed-star.spica', label: 'Spica' },
      { id: 'heze', x: 220, y: 150, mag: 4, canonicalName: 'astrology.fixed-star.heze', label: 'Heze' },
      { id: 'syrma', x: 220, y: 220, mag: 4, canonicalName: 'astrology.fixed-star.syrma', label: 'Syrma' },
    ],
    lines: [
      ['head', 'vindemiatrix'],
      ['head', 'wing_left'],
      ['head', 'waist'],
      ['waist', 'spica'],
      ['vindemiatrix', 'heze'],
      ['heze', 'syrma'],
    ],
  },
  'aquila': {
    viewBox: '0 0 260 270',
    stars: [
      { id: 'tarazed', x: 150, y: 50, mag: 3, canonicalName: 'astrology.fixed-star.tarazed', label: 'Tarazed' },
      { id: 'altair', x: 150, y: 120, mag: 1, canonicalName: 'astrology.fixed-star.altair', label: 'Altair' },
      { id: 'alshain', x: 150, y: 190, mag: 3, canonicalName: 'astrology.fixed-star.alshain', label: 'Alshain' },
      { id: 'wing_l', x: 90, y: 120, mag: 4 },
      { id: 'wing_r', x: 210, y: 120, mag: 4 },
      { id: 'deneb_el_okab', x: 150, y: 235, mag: 3, canonicalName: 'astrology.fixed-star.deneb-el-okab', label: 'Deneb el Okab' },
    ],
    lines: [
      ['tarazed', 'altair'],
      ['altair', 'alshain'],
      ['wing_l', 'altair'],
      ['altair', 'wing_r'],
      ['alshain', 'deneb_el_okab'],
    ],
  },
  'aquarius': {
    viewBox: '0 0 300 280',
    stars: [
      { id: 'sadalmelik', x: 110, y: 50, mag: 3, canonicalName: 'astrology.fixed-star.sadalmelik', label: 'Sadalmelik' },
      { id: 'sadalsuud', x: 190, y: 50, mag: 2, canonicalName: 'astrology.fixed-star.sadalsuud', label: 'Sadalsuud' },
      { id: 'jar', x: 150, y: 120, mag: 4, canonicalName: 'astrology.fixed-star.sadachbia', label: 'Sadachbia' },
      { id: 'stream1', x: 170, y: 190, mag: 4, canonicalName: 'astrology.fixed-star.skat', label: 'Skat' },
      { id: 'stream2', x: 190, y: 260, mag: 4, canonicalName: 'astrology.fixed-star.seat', label: 'Seat' },
      { id: 'sadaltager', x: 100, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.sadaltager', label: 'Sadaltager' },
      { id: 'albali', x: 230, y: 130, mag: 4, canonicalName: 'astrology.fixed-star.albali', label: 'Albali' },
      { id: 'ancha', x: 250, y: 80, mag: 4, canonicalName: 'astrology.fixed-star.ancha', label: 'Ancha' },
      { id: 'leg_l', x: 60, y: 20, mag: 5 },
      { id: 'leg_r', x: 130, y: 15, mag: 5 },
    ],
    lines: [
      ['sadalmelik', 'jar'],
      ['sadalsuud', 'jar'],
      ['jar', 'stream1'],
      ['stream1', 'stream2'],
      ['jar', 'sadaltager'],
      ['sadalsuud', 'albali'],
      ['albali', 'ancha'],
      ['sadalmelik', 'leg_l'],
      ['sadalsuud', 'leg_r'],
    ],
  },
}
