/**
 * geocoder.ts
 * Offline city search backed by /geodata/cities.json — a prefix-indexed dataset
 * generated by scripts/seed-geodata.mjs (starter) or scripts/build-geodata.mjs
 * (full GeoNames dataset).
 *
 * No network requests are made at runtime; the JSON is loaded once on first
 * search and then cached in memory.
 */

export type CityResult = {
  displayName: string   // "Paris"
  admin1: string        // "Île-de-France"
  countryCode: string   // "FR"
  country: string       // "France"
  lat: number
  lon: number
  timezone: string      // IANA, e.g. "Europe/Paris"
}

// [displayName, asciiName, countryCode, admin1, lat, lon, timezone]
type CityRow = [string, string, string, string, number, number, string]

interface GeoDatabase {
  v: number
  countries: Record<string, string>
  cities: CityRow[]
  index: Record<string, [number, number]>
  tzCentroids: Record<string, [number, number]>
}

let _db: GeoDatabase | null = null
let _loading: Promise<GeoDatabase | null> | null = null

async function getDatabase(): Promise<GeoDatabase | null> {
  if (_db) return _db
  if (_loading) return _loading
  _loading = fetch('/geodata/cities.json')
    .then(r => { if (!r.ok) { console.warn('[geocoder] cities.json not found:', r.status); return null } return r.json() as Promise<GeoDatabase> })
    .then(data => { if (data) _db = data; return data })
    .catch(err => { console.warn('[geocoder] failed to load cities.json:', err); return null })
  return _loading
}

/** Lowercase + strip diacritics for accent-insensitive matching. */
function normalize(s: string): string {
  return s.toLowerCase().normalize('NFD').replace(/\p{M}/gu, '')
}

/**
 * Search for cities matching the query string.
 * Returns up to `limit` results ranked by match quality (exact > prefix > contains).
 * Returns [] if the database isn't loaded or the query is < 2 characters.
 */
export async function searchCities(query: string, limit = 8): Promise<CityResult[]> {
  const db = await getDatabase()
  if (!db || query.trim().length < 3) return []

  const q      = normalize(query.trim())
  const prefix = q.slice(0, 3)
  const entry  = db.index[prefix]
  if (!entry) return []

  const [start, count] = entry
  const candidates = db.cities.slice(start, start + count)

  type Scored = { r: CityResult; score: number }
  const scored: Scored[] = []

  for (const c of candidates) {
    const ascii = normalize(c[1])
    if (!ascii.includes(q)) continue
    const score = ascii === q ? 3 : ascii.startsWith(q) ? 2 : 1
    scored.push({
      r: {
        displayName: c[0],
        admin1:      c[3],
        countryCode: c[2],
        country:     db.countries[c[2]] ?? c[2],
        lat:         c[4],
        lon:         c[5],
        timezone:    c[6],
      },
      score,
    })
  }

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.r)
}

/**
 * Returns true once the city database has been fetched and loaded.
 * Kicks off loading as a side effect if not already started.
 */
export async function geodataReady(): Promise<boolean> {
  const db = await getDatabase()
  return db !== null && db.cities.length > 0
}

/**
 * Approximate coordinates for an IANA timezone ID, derived from the
 * population-weighted centroid of cities in that zone.
 * Returns null if the timezone is unknown or the database isn't loaded.
 */
export function getTimezoneCentroid(tzId: string): { lat: number; lon: number } | null {
  const c = _db?.tzCentroids?.[tzId]
  return c ? { lat: c[0], lon: c[1] } : null
}

/** Trigger database prefetch without waiting. Call on app startup or form mount. */
export function prefetchGeodata(): void {
  getDatabase().catch(() => {/* silently ignore */})
}
